version: '3'

services:

  filemgr:
    image: oodt/filemgr:latest
    restart: "no"
    ports:
      - 9000:9000
      - 5005:5005
    environment:
      - SOLR_URL=http://solr:8983
      - DEBUG=5005

  opsui:
    image: oodt/opsui:latest
    restart: "no"
    ports:
      - 5000:5000

  tomcat:
    image: oodt/tomcat:latest
    restart: "no"
    ports:
      - 8080:8080
    environment:
      FILEMGR_URL: http://filemgr:9000
      WORKFLOW_URL: http://wmgr:9001
      FILEMGR_DATATRANSFER_FACTORY: org.apache.oodt.cas.filemgr.datatransfer.RemoteDataTransferFactory
      FILEMGR_WORKINGDIR: /tmp
